project:
  type: website

website:
  title: "Proyecto Almacenes y Mineria de Datos"
  sidebar:
    style: "docked"
    search: true
    contents:
    - text: "Introduction"
      href: index.qmd
    - section: "E0"
      href: entregas/E0_comprension_negocio/bitacora.qmd
      contents:
          - entregas/E0_comprension_negocio/bitacora.qmd
          - entregas/E0_comprension_negocio/canvas.qmd
          - entregas/E0_comprension_negocio/criterio_exito.qmd
          - entregas/E0_comprension_negocio/preguntas.qmd
          - entregas/E0_comprension_negocio/riesgos_supuestos.qmd
          - entregas/E0_comprension_negocio/uso_ia.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



