---
title: "Preguntas de investigación, segunda version"
---

## Contexto

Después de la entrevista con la Dra. María Victoria Guzmán Sánchez, y de conocer más a profundidad la situación sobre los problemas de optimización de la biblioteca, pudimos darnos cuenta de que la cuestión no se limita únicamente al espacio físico en las estanterías ocupado por libros que no son consultados, sino que los espacios comunes se ven afectados de igual manera.

Teniendo en cuenta que nuestro objetivo de minería de datos es:

> **Analizar los patrones de uso de los libros dentro del acervo histórico para su posterior evaluación y descarte.**

Las preguntas que guiarán este proyecto son las siguientes.

## Preguntas de investigación

### [P1] Pregunta 1 — Prioridad alta

¿Qué libros dentro del acervo histórico de la biblioteca de la Facultad de Ciencias se encuentran en el catálogo y no son localizables en el acervo?

### [P2] Pregunta 2 — Prioridad alta

¿Cuáles son las características comunes en la signatura topográfica de los ejemplares con menos préstamos dentro del acervo histórico de la biblioteca de la Facultad de Ciencias?

### [P3] Pregunta 3 — Prioridad alta

¿Qué criterios determinan qué libros deberían ser descartados?

### [P4] Pregunta 4 — Prioridad alta

¿Qué factores influyen para que un libro deje de ser relevante?
